src/Entity/AiUser.php
<?php

namespace App\Entity;

use App\Entity\AiRole;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use App\Repository\AiUserRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=AiUserRepository::class)
 * @ORM\Table(name="ai_users")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class AiUser implements UserInterface, PasswordAuthenticatedUserInterface
{

    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Cette valeur ne doit pas être vide.")
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="datetime", length=255, nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $birthPlace;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;


    /**
     * @ORM\ManyToMany(targetEntity=AiRole::class, inversedBy="aiUsers")
     */
    private $aiRoles;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $avatar;

    /**
     * @Vich\UploadableField(mapping="avatars", fileNameProperty="avatar")
     * @Assert\NotBlank(message="Vous devez avoir une image.")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $confirmAt;


    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\ManyToOne(targetEntity=AiStudentInformation::class, inversedBy="users")
     */
    private $studentInformation;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=AiTeacherInformation::class, mappedBy="user")
     */
    private $teacherInformations;

    /**
     * @ORM\OneToMany(targetEntity=AiMessage::class, mappedBy="sender")
     */
    private $messagesSent;

    /**
     * @ORM\OneToMany(targetEntity=AiMessage::class, mappedBy="receiver")
     */
    private $messagesReceived;



    public function __construct()
    {
        $this->aiRoles = new ArrayCollection();
        $this->teacherInformations = new ArrayCollection();
        $this->messagesSent = new ArrayCollection();
        $this->messagesReceived = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, AiRole>
     */
    public function getAiRoles(): Collection
    {
        return $this->aiRoles;
    }

    public function addAiRole(AiRole $aiRole): self
    {
        if (!$this->aiRoles->contains($aiRole)) {
            $this->aiRoles[] = $aiRole;
        }

        return $this;
    }

    public function removeAiRole(AiRole $aiRole): self
    {
        $this->aiRoles->removeElement($aiRole);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $userRoles = $this->getAiRoles();
        $roles = [];
        foreach ($userRoles as $userRole) {
            $roles[] = $userRole->getName();
        }
        return array_unique($roles);
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getFullName()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getFullBirth()
    {

        return $this->birthDate->format('d-m-Y') . ' à ' . $this->birthPlace;
    }

    public function getConfirmAt(): ?\DateTimeInterface
    {
        return $this->confirmAt;
    }

    public function setConfirmAt(?\DateTimeInterface $confirmAt): self
    {
        $this->confirmAt = $confirmAt;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getBirthPlace(): ?string
    {
        return $this->birthPlace;
    }

    public function setBirthPlace(string $birthPlace): self
    {
        $this->birthPlace = $birthPlace;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getStudentInformation(): ?AiStudentInformation
    {
        return $this->studentInformation;
    }

    public function setStudentInformation(?AiStudentInformation $studentInformation): self
    {
        $this->studentInformation = $studentInformation;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, AiTeacherInformation>
     */
    public function getTeacherInformations(): Collection
    {
        return $this->teacherInformations;
    }

    public function addTeacherInformation(AiTeacherInformation $teacherInformation): self
    {
        if (!$this->teacherInformations->contains($teacherInformation)) {
            $this->teacherInformations[] = $teacherInformation;
            $teacherInformation->setUser($this);
        }

        return $this;
    }

    public function removeTeacherInformation(AiTeacherInformation $teacherInformation): self
    {
        if ($this->teacherInformations->removeElement($teacherInformation)) {
            // set the owning side to null (unless already changed)
            if ($teacherInformation->getUser() === $this) {

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


class SecurityController extends AbstractController
{
    /**
     * @Route("/login-bo", name="app_login_bo", priority=10)
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('app_home');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login-bo.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/check-user-connected/bo", name="app_login_success_check", priority=20)
     */
    public function checkUserConnectedBo(): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login_bo');
        } else {
            $user = $this->getUser();
            if (in_array("ROLE_ADMIN", $user->getRoles(), true)) {
                return $this->redirectToRoute('app_admin_home');
            } else if (in_array("ROLE_SCHOOL_MANAGER", $user->getRoles(), true)) {
                return $this->redirectToRoute('app_school_manager_home');
            } else if (in_array("ROLE_TEACHER", $user->getRoles(), true)) {
                return $this->redirectToRoute('app_teacher_home');
            }
        }
        return $this->redirectToRoute('app_login_bo');
    }

    /**
     * @Route("/logout", name="app_logout",priority=9)
     */
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login-bo.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Authentification | AELI AFRICA</title>
		<link rel="icon" href="../wp-content/uploads/2022/07/cropped-logo-2-32x32.png" sizes="32x32"/>
		<link rel="stylesheet" href="{{ asset('assets/BO/plugins/fontawesome-free/css/all.min.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/BO/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/BO/dist/css/adminlte.min.css') }}">
	</head>
	<body class="hold-transition login-page">
		<div class="login-box">
			<div class="card card-outline card-primary">
				<div class="card-header text-center">
					<a href="{{ path('app_home') }}" class="h1">
						<b>AELI</b>
						AFRICA
					</a>
				</div>
				<div class="card-body">
					<p class="login-box-msg">Connectez-vous pour démarrer votre session</p>
					<form method="post">
						{% if error %}
							<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
						{% endif %}
						{% if app.user %}
							<div class="mb-3">
								Vous êtes connecté en tant que
								{{ app.user.userIdentifier }},
								<a href="{{ path('app_logout') }}">Se déconnecter</a>
							</div>
						{% endif %}
						<div class="input-group mb-3">
							<input type="email" placeholder="e-mail" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
							<div class="input-group-append">
								<div class="input-group-text">
									<span class="fas fa-envelope"></span>
								</div>
							</div>
						</div>
						<div class="input-group mb-3">
							<input type="password" placeholder="le mot de passe" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
							<div class="input-group-append">
								<div class="input-group-text">
									<span class="fas fa-lock"></span>
								</div>
							</div>
						</div>
						<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
						<div class="row">
							<div class="col-8">
								<div class="icheck-primary">
									<input type="checkbox" name="_remember_me" id="remember">
									<label for="remember">
										Souviens-toi de moi
									</label>
								</div>
							</div>
							<div class="col-4">
								<button type="submit" class="btn btn-primary">S'identifier</button>
							</div>
						</div>
					</form>
					<p class="mb-1 mt-3">
						<a href="{{ path('app_forgot_password_request') }}">J'ai oublié mon mot de passe</a>
					</p>
				</div>
			</div>
		</div>
		<script src="{{ asset('assets/BO/plugins/jquery/jquery.min.js') }}"></script>
		<script src="{{ asset('assets/BO/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
		<script src="{{ asset('assets/BO/dist/js/adminlte.js') }}"></script>
	</body>
</html>

templates/security/login-student.html.twig
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Authentification | AELI AFRICA</title>
		<link rel="icon" href="../wp-content/uploads/2022/07/cropped-logo-2-32x32.png" sizes="32x32"/>
		<link rel="stylesheet" href="{{ asset('assets/BO/plugins/fontawesome-free/css/all.min.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/BO/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/BO/dist/css/adminlte.min.css') }}">
	</head>
	<body class="hold-transition login-page">
		<div class="login-box">
			<div class="card card-outline card-primary">
				<div class="card-header text-center">
					<a href="{{ path('app_home') }}" class="h1">
						<b>AELI </b>
						AFRICA
					</a>
				</div>
				<div class="card-body">
					<p class="login-box-msg">Connectez-vous pour démarrer votre session</p>
					<form method="post">
						{% if error %}
							<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
						{% endif %}
						{% if app.user %}
							<div class="mb-3">
								Vous êtes connecté en tant que
								{{ app.user.userIdentifier }},
								<a href="{{ path('app_logout') }}">Se déconnecter</a>
							</div>
						{% endif %}

						<div class="input-group mb-3">
							<input type="text" placeholder="votre numero matricule" name="matriculeNumber" id="inputMatriculeNumber" class="form-control" required autofocus>
							<div class="input-group-append">
								<div class="input-group-text">
									<span class="fas fa-user"></span>
								</div>
							</div>
						</div>

						<div class="input-group mb-3">
							<input type="email" placeholder="e-mail" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required>
							<div class="input-group-append">
								<div class="input-group-text">
									<span class="fas fa-envelope"></span>
								</div>
							</div>
						</div>
						<div class="input-group mb-3">
							<input type="password" placeholder="le mot de passe" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
							<div class="input-group-append">
								<div class="input-group-text">
									<span class="fas fa-lock"></span>
								</div>
							</div>
						</div>
						<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
						<div class="row">
							<div class="col-8">
								<div class="icheck-primary">
									<input type="checkbox" name="_remember_me" id="remember">
									<label for="remember">
										Souviens-toi de moi
									</label>
								</div>
							</div>
							<div class="col-4">
								<button type="submit" class="btn btn-primary">S'identifier</button>
							</div>
						</div>
					</form>
					<p class="mb-1 mt-3">
						<a href="{{ path('app_forgot_password_request') }}">J'ai oublié mon mot de passe</a>
					</p>
					<p class="mb-0">
						<a href="{{ path('app_register') }}" class="text-center">Inscrivez-vous ici</a>
					</p>
				</div>
			</div>
		</div>
		<script src="{{ asset('assets/BO/plugins/jquery/jquery.min.js') }}"></script>
		<script src="{{ asset('assets/BO/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
		<script src="{{ asset('assets/BO/dist/js/adminlte.js') }}"></script>
	</body>
</html>