src/Entity/AiUser.php
<?php

namespace App\Entity;

use App\Entity\AiRole;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use App\Repository\AiUserRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=AiUserRepository::class)
 * @ORM\Table(name="ai_users")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class AiUser implements UserInterface, PasswordAuthenticatedUserInterface
{

    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Cette valeur ne doit pas être vide.")
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="datetime", length=255, nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $birthPlace;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;


    /**
     * @ORM\ManyToMany(targetEntity=AiRole::class, inversedBy="aiUsers")
     */
    private $aiRoles;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $avatar;

    /**
     * @Vich\UploadableField(mapping="avatars", fileNameProperty="avatar")
     * @Assert\NotBlank(message="Vous devez avoir une image.")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $confirmAt;


    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\ManyToOne(targetEntity=AiStudentInformation::class, inversedBy="users")
     */
    private $studentInformation;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=AiTeacherInformation::class, mappedBy="user")
     */
    private $teacherInformations;

    /**
     * @ORM\OneToMany(targetEntity=AiMessage::class, mappedBy="sender")
     */
    private $messagesSent;

    /**
     * @ORM\OneToMany(targetEntity=AiMessage::class, mappedBy="receiver")
     */
    private $messagesReceived;



    public function __construct()
    {
        $this->aiRoles = new ArrayCollection();
        $this->teacherInformations = new ArrayCollection();
        $this->messagesSent = new ArrayCollection();
        $this->messagesReceived = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, AiRole>
     */
    public function getAiRoles(): Collection
    {
        return $this->aiRoles;
    }

    public function addAiRole(AiRole $aiRole): self
    {
        if (!$this->aiRoles->contains($aiRole)) {
            $this->aiRoles[] = $aiRole;
        }

        return $this;
    }

    public function removeAiRole(AiRole $aiRole): self
    {
        $this->aiRoles->removeElement($aiRole);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $userRoles = $this->getAiRoles();
        $roles = [];
        foreach ($userRoles as $userRole) {
            $roles[] = $userRole->getName();
        }
        return array_unique($roles);
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getFullName()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getFullBirth()
    {

        return $this->birthDate->format('d-m-Y') . ' à ' . $this->birthPlace;
    }

    public function getConfirmAt(): ?\DateTimeInterface
    {
        return $this->confirmAt;
    }

    public function setConfirmAt(?\DateTimeInterface $confirmAt): self
    {
        $this->confirmAt = $confirmAt;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getBirthPlace(): ?string
    {
        return $this->birthPlace;
    }

    public function setBirthPlace(string $birthPlace): self
    {
        $this->birthPlace = $birthPlace;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getStudentInformation(): ?AiStudentInformation
    {
        return $this->studentInformation;
    }

    public function setStudentInformation(?AiStudentInformation $studentInformation): self
    {
        $this->studentInformation = $studentInformation;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, AiTeacherInformation>
     */
    public function getTeacherInformations(): Collection
    {
        return $this->teacherInformations;
    }

    public function addTeacherInformation(AiTeacherInformation $teacherInformation): self
    {
        if (!$this->teacherInformations->contains($teacherInformation)) {
            $this->teacherInformations[] = $teacherInformation;
            $teacherInformation->setUser($this);
        }

        return $this;
    }

    public function removeTeacherInformation(AiTeacherInformation $teacherInformation): self
    {
        if ($this->teacherInformations->removeElement($teacherInformation)) {
            // set the owning side to null (unless already changed)
            if ($teacherInformation->getUser() === $this) {

src/Controller/Student/CalendarController.php
<?php

namespace App\Controller\Student;

use App\Repository\IeTimetableRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/student", priority=10)
 */
class CalendarController extends AbstractController
{

    /**
     * @Route("/calendar/show", name="app_student_calendar_show")
     */
    public function show(): Response
    {
        return $this->render('student/calendar/show.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' calendar'
        ]);
    }

    /**
     * @Route("/calendar/get-data", name="app_student_calendar_get_data")
     */
    public function getData(
        IeTimetableRepository $ieTimetableRepository

    ): Response {

        $timetables = $ieTimetableRepository->getTimetables($this->getUser()->getStudentInformation());
        $data = [];
        foreach ($timetables as $timetable) {
            array_push($data, [
                'title' => $timetable->getTitle(),
                'start' => $timetable->getStartAt(),
                'end' => $timetable->getEndAt(),
                'backgroundColor' => $timetable->getColor(),
                'borderColor' => $timetable->getColor(),
            ]);
        }

        // on récupère la date d'entrée
        $enterDate = $this->getUser()->getStudentInformation()->getVague()->getStartAt();
        if ($enterDate) {
            array_push($data, [
                'title' => "Date d'entrée pour la " . $this->getUser()->getStudentInformation()->getVague(),
                'start' => $enterDate,
                'backgroundColor' => "red",
                'borderColor' => "red",
                'allDay' => true,
            ]);
        }

        return $this->json($data);
    }
}

src/Controller/Student/CourseController.php
<?php

namespace App\Controller\Student;

use App\Entity\AiCourse;
use App\Entity\AiTaught;
use App\Entity\AiCourseContent;
use App\Repository\AiVagueRepository;
use App\Repository\AiTaughtRepository;
use App\Repository\AiCourseContentRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/student", priority=10)
 */
class CourseController extends AbstractController
{

    /**
     * @Route("/course", name="app_student_course")
     */
    public function index(
        AiVagueRepository $aiVagueRepository,
        AiTaughtRepository $aiTaughtRepository
    ): Response {
        $user = $this->getUser();
        $studentInformation = $this->getUser()->getStudentInformation();
        $studentInformationVauge = $studentInformation->getVague();
        $vagueFound = $aiVagueRepository->findOneByVNumber($studentInformationVauge);
        if ($vagueFound) {
            $dateEnter = $vagueFound->getStartAt();
            $now = new \DateTimeImmutable("now");
            $diff = $dateEnter->diff($now, true);
            $monthDiff = ($diff->m) + 1; // + 1 : pour avoir le différence mois 0
            $formationforStudents = $ieTaughtRepository->getAvalaibleCourse($studentInformation, $monthDiff);
        }
        return $this->render('student/course/index.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' course',
            'user' => $user,
            'formationforStudents' => $formationforStudents,
        ]);
    }


    /**
     * @Route("/course/{slug}", name="app_student_course_show")
     */
    public function show(AiCourse $aiCourse, AiCourseContentRepository $aiCourseContentRepository): Response
    {
        $user = $this->getUser();
        $courseContents = $aiCourseContentRepository->getCourse($aiCourse, "LESSON");
        return $this->render('student/course/show.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' course',
            'courseContents' => $courseContents,
            'course' => $aiCourse,
        ]);
    }

    /**
     * @Route("/download/course/content/file/{id}", name="app_student_course_download_file")
     */
    public function downloadFile(
        AiCourseContent $aiCourseContent
    ): Response {

        return $this->file('uploads/courses/content/' . $aiCourseContent->getFile());
    }
}

src/Controller/Student/ExamenController.php
<?php

namespace App\Controller\Student;

use App\Entity\AiCourse;
use App\Entity\AiTaught;
use App\Repository\AiVagueRepository;
use App\Repository\AiTaughtRepository;
use App\Repository\AiCourseContentRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/student/examen", priority=10)
 */
class ExamenController extends AbstractController
{

    /**
     * @Route("/", name="app_student_examen")
     */
    public function index(): Response
    {
        dd('examen');
        return $this->render('student/course/index.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' no',
        ]);
    }
}

src/Controller/Student/HelpController.php
<?php

namespace App\Controller\Student;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/student", priority=10)
 */
class HelpController extends AbstractController
{

    /**
     * @Route("/help", name="app_student_help")
     */
    public function index(): Response
    {
        $user = $this->getUser();
        return $this->render('student/help/index.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' help',
            'user' => $user
        ]);
    }
}

src/Controller/Student/MessageController.php
<?php

namespace App\Controller\Student;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/student", priority=10)
 */
class MessageController extends AbstractController
{

    /**
     * @Route("/message", name="app_student_message")
     */
    public function index(): Response
    {
        $user = $this->getUser();
        return $this->render('student/message/index.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' message',
            'user' => $user
        ]);
    }

    /**
     * @Route("/message/video/chat", name="app_student_message_video_chat")
     */
    public function videoChat(): Response
    {
        $user = $this->getUser();
        return $this->render('student/message/video-chat/index.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' message',
            'user' => $user
        ]);
    }

    /**
     * @Route("/message/video/chat/room/{key}", name="app_student_message_video_chat_room")
     */
    public function room($key): Response
    {
        $user = $this->getUser();
        $link = hex2bin($key);
        return $this->render('student/message/video-chat/index.html.twig', [
            'disableAllMenu' => false,
            'activeMenu' => ' message',
            'link' => $link,
            'user' => $user
        ]);
    }

    /**
     * @Route("/message/video/chat/justify", name="app_student_message_video_chat_key")
     */
    public function justify(Request $request): Response
    {
        $user = $this->getUser();
        $keywords = $request->request->get('keywords', '');
        return $this->redirectToRoute('app_student_message_video_chat_room', ['key' => bin2hex($keywords)]);
    }
}

templates/student/profil/show.html.twig
{% extends "student/st.html.twig" %}
{% block title %}
	Votre profil
	{{ parent() }}
{% endblock %}
{% block body %}
	<div class="wrapper">
		{{ include('student/layouts/nav-bar.html.twig') }}
		{{ include('student/layouts/aside-bar.html.twig') }}


		<div class="content-wrapper">
			<section class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-lg-12 font-italic">
							<h1>Profil</h1>
						</div>
					</div>
				</div>
			</section>
			{% set student = user.studentInformation %}
			<section class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-3">
							<div class="card card-info card-outline">
								<div class="card-body box-profile">
									<div class="text-center">
										{% if user.avatar is defined and user.avatar is not empty %}
											<img src="{{ vich_uploader_asset(user) | imagine_filter('AVATAR') }}" class="profile-user-img img-fluid img-circle" alt="User Image">
										{% else %}
											<img src="{{ asset('images/user-default-image.png') }}" class="profile-user-img img-fluid img-circle" alt="User Image">
										{% endif %}
									</div>

									<h3 class="profile-username text-center">{{ student.matriculeNumber }}</h3>


									<p class="text-muted text-center">{{ user.email }}</p>
									<hr>
									<strong>
										<i class="fas fa-user mr-1"></i>
										nom complet</strong>
									<p class="text-muted">
										{{ user.fullName }}
									</p>
									<hr>
									<strong>
										<i class="fas fa-birthday-cake mr-1"></i>
										Date et lieu de naissance</strong>
									<p class="text-muted">
										{{ user.birthDate | date('d-m-Y') ~ " à " ~ user.birthPlace}}
									</p>
									<hr>
									<strong>
										<i class="fas fa-phone mr-1"></i>
										Contact et adresse</strong>
									<p class="text-muted">
										{{ user.phoneNumber }},
										{{ user.address }}
									</p>
									<hr>
									<strong>
										<i class="fas fa-calendar mr-1"></i>
										Date de validation d'inscription</strong>
									<p class="text-muted">
										{{ user.confirmAt | date('d-m-Y h:i:s') }}
									</p>


								</div>
							</div>

						</div>
						<!-- /.col -->
						<div class="col-md-9">
							<div class="card">
								<div class="card-header p-2">
									<ul class="nav nav-pills">
										<li class="nav-item">
											<a class="nav-link active" href="#infoUniv" data-toggle="tab">Information universitaire</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" href="#rengGaran" data-toggle="tab">Renseignemets des garants</a>
										</li>
									</ul>
								</div>
								<!-- /.card-header -->
								<div class="card-body">
									<div class="tab-content">
										<div class="active tab-pane" id="infoUniv">
											<div class="row">
												<div class="col-lg-12">
													<ul class="list-group">
														<li class="list-group-item d-flex justify-content-between align-items-center">
															<b>Type de formation</b>
															<span class="badge badge-info badge-pill">{{ getFormationType(student.formationType) }}</span>
														</li>
														<li class="list-group-item d-flex justify-content-between align-items-center">
															<b>Filière</b>
															<span class="badge badge-info badge-pill">{{ student.faculty }}</span>
														</li>
														<li class="list-group-item d-flex justify-content-between align-items-center">
															<b>Niveau</b>
															<span class="badge badge-info badge-pill">{{ student.level }}</span>
														</li>
														<li class="list-group-item d-flex justify-content-between align-items-center">
															<b>Semestre</b>
															<span class="badge badge-info badge-pill">{{ student.semester }}</span>
														</li>
														<li class="list-group-item d-flex justify-content-between align-items-center">
															<b>Vague</b>
															<span class="badge badge-info badge-pill">{{ student.vague }}</span>
														</li>
													</ul>
													<br>
													<h5>Service technique</h5>
													<table class="table sm table-striped table-bordered">
														<tr>
															<th></th>
															<th>lorem</th>
															<th>ipsum</th>
															<th>dolor</th>
															<th>sit amet</th>
														</tr>
														<tr>
															<th>E-mail</th>
															<td>lorem</td>
															<td>ipsum</td>
															<td>dolor</td>
															<td>sit amet</td>
														</tr>
														<tr>
															<th>Numero</th>
															<td>lorem</td>
															<td>ipsum</td>
															<td>dolor</td>
															<td>sit amet</td>
														</tr>

													</table>
												</div>
											</div>
										</div>
										<div class="tab-pane" id="rengGaran">
											<div class="card">
												<div class="card-header">
													<h3 class="card-title">
														<i class="fas fa-text-width"></i>
														Renseignement des garants pour les étudiants
														<span class="badge badge-info">{{getType(user.studentInformation.type ~ '.' ~ user.studentInformation.sexe)}}

														</span>
													</h3>
												</div>
												<div class="card-body">
													<dl class="row">

														{% if user.studentInformation.type == "worker" %}
															<dt class="col-sm-5">Fonction</dt>
															<dd class="col-sm-7">{{ user.studentInformation.job }}</dd>
															<dt class="col-sm-5">Nom de l'employeur</dt>
															<dd class="col-sm-7">{{ user.studentInformation.employerName }}</dd>
															<dt class="col-sm-5">Nom du garant</dt>
															<dd class="col-sm-7">{{ user.studentInformation.gNames }}</dd>
															<dt class="col-sm-5">E-mail</dt>
															<dd class="col-sm-7">{{ user.studentInformation.gEmail }}</dd>
															<dt class="col-sm-5">Contact</dt>
															<dd class="col-sm-7">{{ user.studentInformation.gPhoneNumber }}</dd>
														{% endif %}

														{% if user.studentInformation.type == "bachelor" %}

															<dt class="col-sm-5">Nom et prénom(s) du père ou de la mère</dt>
															<dd class="col-sm-7">{{ user.studentInformation.fmNames }}</dd>
															<dt class="col-sm-5">Fonction</dt>
															<dd class="col-sm-7">{{ user.studentInformation.fmJobs }}</dd>
															<dt class="col-sm-5">E-mail</dt>
															<dd class="col-sm-7">{{ user.studentInformation.fmEmail }}</dd>
															<dt class="col-sm-5">Contact</dt>
															<dd class="col-sm-7">{{ user.studentInformation.fmPhoneNumber }}</dd>
															<dt class="col-sm-5">Adresse</dt>
															<dd class="col-sm-7">{{ user.studentInformation.fmAdress }}</dd>
															<dt class="col-sm-5">Nom et prénom(s) du tuteur ou de la tutrice</dt>
															<dd class="col-sm-7">{{ user.studentInformation.tNames }}</dd>
															<dt class="col-sm-5">Fonction</dt>
															<dd class="col-sm-7">{{ user.studentInformation.tJobs }}</dd>
															<dt class="col-sm-5">E-mail</dt>
															<dd class="col-sm-7">{{ user.studentInformation.tEmail }}</dd>
															<dt class="col-sm-5">Contact</dt>
															<dd class="col-sm-7">{{ user.studentInformation.tPhoneNumber }}</dd>
															<dt class="col-sm-5">Adresse</dt>
															<dd class="col-sm-7">{{ user.studentInformation.tAdress }}</dd>


														{% endif %}

													</dl>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

		</div>
	</div>

{% endblock %}